ruby/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index]
  resources :listings, only: [:index]

  root "categories#index"
end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = search_categories(params[:query])
  end


  private

  def search_categories(query)
    return [] if query.blank?
    load_categories.select do |category|
      category['full_name'].downcase.include?(query.downcase)
    end
  end

  def load_categories
    ReverbClient.new.categories
  end
end

ruby/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = ::ReverbClient.new.listings
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/views/categories/index.html.erb
<%= form_tag(categories_path, method: :get) do -%>
  <div class="form-group">
    <label for="query">Category Search</label>
    <input class="form-control" type="text" name="query" placeholder="Enter Category Name">
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>

<% if @categories.present? %>
  <ul class="list-group">
    <% @categories.each do |category| %>
      <li class="list-group-item">
        <%= category['full_name'] %>
      </li>
    <% end %>
  </ul>
<% elsif params[:query].present? %>
  <p>Sorry. No results were found for your search.</p>
<% end %>

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reverb Ruby Extension</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-info">
      <%= link_to('Reverb API', root_path, class: 'navbar-brand') -%>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to('Categories', categories_path, class: 'nav-link') -%>
        </li>
        <li class="nav-item">
          <%= link_to('Listings', listings_path, class: 'nav-link') -%>
        </li>
      </ul>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

ruby/app/views/listings/index.html.erb
<% if @listings.present? %>
  <ul class="list-group">
    <% @listings.each do |listing| %>
      <li class="d-flex list-group-item flex-row align-items-center">
        <div class="p-2">
            <%= image_tag(listing['photos'].first['_links']['thumbnail']['href'] )%>
        </div>
        <h2 class="p-2">
            <%= listing['title'] %>
        </h2>
      </li>
    <% end %>
  </ul>
<% end %>